// README
/* CalculaEVAN es un programa le permite al usario saber si se encuentra por encima o debajo
de la Esperanza de vida al nacer (EVAN) para su país de nacimiento, su edad actual y género.
Pide los datos del usuario, tales como nombre, edad, sexo y país de nacimiento
y devuelve la diferencia entre la EVAN y la edad de la persona en años e imprime en pantalla
cuantos años le quedan por vivir en caso que su edad sea inferior a la EVAN o en caso contrario indica cuantos
años más ha vivido que el promedio para su grupo etario y país de nacimiento.*/

// FUENTE: www.datosmacro.expansion.com

package main

import (
	"errors"
	"fmt"
	"strings"
)

//Persona define los diferentes campos para una persona.
type Persona struct {
	Nombre string
	Edad   int
	Sexo   string
	Pais   string
}

// EVANH contiene los países y la Esperanza de Vida al Nacer para hombres nacidos en tal país.
var EVANH = map[string]int{
	"España": 81, "Alemania": 79, "Reino Unido": 79, "Francia": 80, "Italia": 81, "Portugal": 78, "Estados Unidos": 75, "Japon": 82, "China": 75, "Andorra": 89,
	"Emiratos Arabes Unidos": 78, "Afganistan": 64, "Antigua y Barbuda": 76, "Albania": 76, "Armenia": 72, "Angola": 59, "Argentina": 74, "Austria": 79, "Australia": 82,
	"Azerbaiyan": 71, "Bosnia y Herzegovina": 76, "Barbados": 78, "Banglades": 72, "Belgica": 80, "Burkina Faso": 62, "Bulgaria": 69, "Barein": 77, "Burundi": 61,
	"Benin": 61, "Brunei": 75, "Bolivia": 69, "Brasil": 73, "Bahamas": 72, "Butan": 72, "Botsuana": 67, "Bielorrusia": 70, "Belice": 72, "Canada": 80, "Republica Democratica del Congo": 60,
	"Republica Centroafricana":        52,
	"Republica del Congo":             64,
	"Suiza":                           82,
	"Costa de Marfil":                 57,
	"Chile":                           78,
	"Camerun":                         59,
	"Colombia":                        75,
	"Costa Rica":                      78,
	"Cuba":                            77,
	"Cabo Verde":                      70,
	"Chipre":                          80,
	"Chequia":                         75,
	"Yibuti":                          66,
	"Dinamarca":                       80,
	"Dominica":                        75,
	"Republica Dominicana":            72,
	"Argelia":                         76,
	"Ecuador":                         75,
	"Estonia":                         73,
	"Egipto":                          70,
	"Eritrea":                         65,
	"Etiopia":                         66,
	"Finlandia":                       80,
	"Fiyi":                            66,
	"Estados Federados de Micronesia": 67,
	"Gabon":                           65,
	"Granada":                         71,
	"Georgia":                         70,
	"Ghana":                           64,
	"Gambia":                          61,
	"Guinea":                          62,
	"Guinea Ecuatorial":               59,
	"Grecia":                          78,
	"Guatemala":                       72,
	"Guinea-Bisau":                    57,
	"Guyana":                          68,
	"Hong Kong":                       83,
	"Honduras":                        74,
	"Croacia":                         74,
	"Haiti":                           63,
	"Hungria":                         72,
	"Indonesia":                       70,
	"Irlanda":                         81,
	"Israel":                          81,
	"India":                           69,
	"Irak":                            69,
	"Iran":                            76,
	"Islandia":                        82,
	"Jamaica":                         73,
	"Jordania":                        73,
	"Kenia":                           65,
	"Kirguistan":                      68,
	"Camboya":                         68,
	"Kiribati":                        65,
	"Comoras":                         63,
	"San Cristobal y Nieves":          69,
	"Corea del Norte":                 69,
	"Corea del Sur":                   81,
	"Kuwait":                          75,
	"Kazajistan":                      68,
	"Laos":                            67,
	"Libano":                          78,
	"Santa Lucia":                     75,
	"Liechtenstein":                   83,
	"Sri Lanka":                       74,
	"Liberia":                         64,
	"Lesoto":                          52,
	"Lituania":                        70,
	"Luxemburgo":                      81,
	"Letonia":                         69,
	"Libia":                           71,
	"Marruecos":                       76,
	"Moldavia":                        68,
	"Montenegro":                      74,
	"Madagascar":                      66,
	"Islas Marshall":                  63,
	"Macedonia del Norte":             73,
	"Mali":                            59,
	"Birmania - Myanmar":              65,
	"Mongolia":                        66,
	"Mauritania":                      64,
	"Malta":                           82,
	"Mauricio":                        71,
	"Maldivas":                        78,
	"Malaui":                          62,
	"Mexico":                          73,
	"Malasia":                         75,
	"Mozambique":                      59,
	"Namibia":                         62,
	"Niger":                           62,
	"Nigeria":                         55,
	"Nicaragua":                       72,
	"Paises Bajos":                    80,
	"Noruega":                         82,
	"Nepal":                           70,
	"Nueva Zelanda":                   81,
	"Oman":                            77,
	"Panama":                          76,
	"Peru":                            75,
	"Papua Nueva Guinea":              64,
	"Filipinas":                       68,
	"Pakistan":                        67,
	"Polonia":                         72,
	"Estado de Palestina":             73,
	"Palaos":                          67,
	"Paraguay":                        73,
	"Catar":                           80,
	"Rumania":                         70,
	"Serbia":                          72,
	"Rusia":                           67,
	"Ruanda":                          68,
	"Arabia Saudita":                  75,
	"Islas Salomon":                   72,
	"Seychelles":                      73,
	"Sudan":                           64,
	"Suecia":                          82,
	"Singapur":                        82,
	"Eslovenia":                       78,
	"Eslovaquia":                      72,
	"Sierra Leona":                    55,
	"San Marino":                      85,
	"Senegal":                         67,
	"Somalia":                         57,
	"Surinam":                         69,
	"Sudan del Sur":                   57,
	"Santo Tome y Principe":           69,
	"El Salvador":                     69,
	"Siria":                           70,
	"Suazilandia":                     57,
	"Chad":                            54,
	"Togo":                            61,
	"Tailandia":                       74,
	"Tayikistan":                      70,
	"Timor Oriental":                  68,
	"Turkmenistan":                    65,
	"Tunez":                           75,
	"Tonga":                           70,
	"Turquia":                         75,
	"Trinidad y Tobago":               71,
	"Tanzania":                        65,
	"Ucrania":                         67,
	"Uganda":                          62,
	"Uruguay":                         75,
	"Uzbekistan":                      70,
	"San Vicente y las Granadinas":    71,
	"Venezuela":                       69,
	"Vietnam":                         72,
	"Vanuatu":                         70,
	"Samoa":                           72,
	"Yemen":                           65,
	"Sudafrica":                       61,
	"Zambia":                          62,
	"Zimbabue":                        61,
}

//EVANM contiene los países y la Esperanza de Vida al Nacer para hombres nacidos en tal país.
var EVANM = map[string]int{
	"España":                          86,
	"Alemania":                        84,
	"Reino Unido":                     83,
	"Francia":                         86,
	"Italia":                          86,
	"Portugal":                        85,
	"Estados Unidos":                  81,
	"Japon":                           88,
	"China":                           80,
	"Andorra":                         92,
	"Emiratos Arabes Unidos":          80,
	"Afganistan":                      67,
	"Antigua y Barbuda":               79,
	"Albania":                         80,
	"Armenia":                         79,
	"Angola":                          65,
	"Argentina":                       81,
	"Austria":                         84,
	"Australia":                       86,
	"Azerbaiyan":                      76,
	"Bosnia y Herzegovina":            80,
	"Barbados":                        81,
	"Banglades":                       75,
	"Belgica":                         85,
	"Burkina Faso":                    63,
	"Bulgaria":                        76,
	"Barein":                          79,
	"Burundi":                         64,
	"Benin":                           64,
	"Brunei":                          78,
	"Bolivia":                         75,
	"Brasil":                          80,
	"Bahamas":                         77,
	"Butan":                           73,
	"Botsuana":                        73,
	"Bielorrusia":                     80,
	"Belice":                          78,
	"Canada":                          84,
	"Republica Democratica del Congo": 63,
	"Republica Centroafricana":        56,
	"Republica del Congo":             67,
	"Suiza":                           86,
	"Costa de Marfil":                 60,
	"Chile":                           83,
	"Camerun":                         61,
	"Colombia":                        81,
	"Costa Rica":                      84,
	"Cuba":                            81,
	"Cabo Verde":                      77,
	"Chipre":                          84,
	"Chequia":                         81,
	"Yibuti":                          70,
	"Dinamarca":                       84,
	"Dominica":                        79,
	"Republica Dominicana":            78,
	"Argelia":                         79,
	"Ecuador":                         81,
	"Estonia":                         82,
	"Egipto":                          75,
	"Eritrea":                         69,
	"Etiopia":                         69,
	"Finlandia":                       85,
	"Fiyi":                            70,
	"Estados Federados de Micronesia": 70,
	"Gabon":                           69,
	"Granada":                         75,
	"Georgia":                         79,
	"Ghana":                           66,
	"Gambia":                          64,
	"Guinea":                          63,
	"Guinea Ecuatorial":               61,
	"Grecia":                          83,
	"Guatemala":                       78,
	"Guinea-Bisau":                    61,
	"Guyana":                          74,
	"Hong Kong":                       88,
	"Honduras":                        78,
	"Croacia":                         80,
	"Haiti":                           67,
	"Hungria":                         78,
	"Indonesia":                       75,
	"Irlanda":                         85,
	"Israel":                          85,
	"India":                           72,
	"Irak":                            73,
	"Iran":                            79,
	"Islandia":                        85,
	"Jamaica":                         77,
	"Jordania":                        77,
	"Kenia":                           70,
	"Kirguistan":                      76,
	"Camboya":                         73,
	"Kiribati":                        73,
	"Comoras":                         67,
	"San Cristobal y Nieves":          74,
	"Corea del Norte":                 76,
	"Corea del Sur":                   87,
	"Kuwait":                          77,
	"Kazajistan":                      76,
	"Laos":                            71,
	"Libano":                          81,
	"Santa Lucia":                     78,
	"Liechtenstein":                   87,
	"Sri Lanka":                       81,
	"Liberia":                         66,
	"Lesoto":                          59,
	"Lituania":                        79,
	"Luxemburgo":                      85,
	"Letonia":                         79,
	"Libia":                           77,
	"Marruecos":                       79,
	"Moldavia":                        77,
	"Montenegro":                      79,
	"Madagascar":                      70,
	"Islas Marshall":                  68,
	"Macedonia del Norte":             77,
	"Mali":                            61,
	"Birmania - Myanmar":              71,
	"Mongolia":                        75,
	"Mauritania":                      67,
	"Malta":                           85,
	"Mauricio":                        78,
	"Maldivas":                        82,
	"Malaui":                          68,
	"Mexico":                          78,
	"Malasia":                         79,
	"Mozambique":                      65,
	"Namibia":                         67,
	"Niger":                           65,
	"Nigeria":                         56,
	"Nicaragua":                       79,
	"Paises Bajos":                    84,
	"Noruega":                         85,
	"Nepal":                           73,
	"Nueva Zelanda":                   84,
	"Oman":                            81,
	"Panama":                          82,
	"Peru":                            80,
	"Papua Nueva Guinea":              67,
	"Filipinas":                       76,
	"Pakistan":                        69,
	"Polonia":                         80,
	"Estado de Palestina":             76,
	"Palaos":                          73,
	"Paraguay":                        77,
	"Catar":                           83,
	"Rumania":                         77,
	"Serbia":                          78,
	"Rusia":                           77,
	"Ruanda":                          72,
	"Arabia Saudita":                  77,
	"Islas Salomon":                   76,
	"Seychelles":                      82,
	"Sudan":                           68,
	"Suecia":                          85,
	"Singapur":                        87,
	"Eslovenia":                       84,
	"Eslovaquia":                      79,
	"Sierra Leona":                    56,
	"San Marino":                      87,
	"Senegal":                         71,
	"Somalia":                         60,
	"Surinam":                         76,
	"Sudan del Sur":                   60,
	"Santo Tome y Principe":           74,
	"El Salvador":                     79,
	"Siria":                           79,
	"Suazilandia":                     66,
	"Chad":                            56,
	"Togo":                            63,
	"Tailandia":                       82,
	"Tayikistan":                      74,
	"Timor Oriental":                  72,
	"Turkmenistan":                    72,
	"Tunez":                           79,
	"Tonga":                           74,
	"Turquia":                         81,
	"Trinidad y Tobago":               77,
	"Tanzania":                        68,
	"Ucrania":                         77,
	"Uganda":                          66,
	"Uruguay":                         82,
	"Uzbekistan":                      74,
	"San Vicente y las Granadinas":    76,
	"Venezuela":                       76,
	"Vietnam":                         80,
	"Vanuatu":                         73,
	"Samoa":                           76,
	"Yemen":                           68,
	"Sudafrica":                       68,
	"Zambia":                          68,
	"Zimbabue":                        64,
}

func main() {
	//Aquí se alojaran todos los campos que recibamos del usuario.
	p1 := Persona{}

	// En los siguientes comandos preguntamos al usuario sus datos
	// y los asignamos a p1.
	fmt.Println("Favor indica tu nombre")
	fmt.Scanln(&p1.Nombre)

	fmt.Println("¿Cuantos años tienes?")
	fmt.Scanln(&p1.Edad)

	fmt.Println("¿Cuál es tu sexo? Masculino, Femenino")
	fmt.Scanln(&p1.Sexo)
	err2 := errors.New("tienes que ingresar un género válido (Masculino o Femenino)")
	if p1.Sexo != strings.ToLower("masculino") || p1.Sexo != strings.ToLower("femenino") {
		panic(err2)
	}

	fmt.Println("Indica país de nacimiento:")
	fmt.Scanln(&p1.Pais)

	// Si el usuario es hombre, calcula e imprime la diferencia entre su edad
	// y los años promedio de vida para hombres de ese país ya sea que los exceda o no.
	if strings.EqualFold(p1.Sexo, "masculino") {
		for key, element := range EVANH {
			switch strings.ToLower(key) {
			case strings.ToLower(p1.Pais):
				if element < p1.Edad {
					fmt.Printf("%s, eres un hombre de %d años, nacido en %v. La EVAN promedio para un hombre en %s es de %d años. Has vivido %d años más que el común de la gente para tu género y país.", p1.Nombre, p1.Edad, key, key, element, (-1 * (element - p1.Edad)))
				} else {
					fmt.Printf("%s, eres un hombre de %d años, nacido en %v. La EVAN promedio para un hombre en %s es de %d años. Te quedan aproximademente %d años más por vivir según tu género y país de nacimiento.", p1.Nombre, p1.Edad, key, key, element, element-p1.Edad)
				}
			}
		}
		// Si el usuario es mujer, calcula e imprime la diferencia entre su edad
		// y EVAN promedio para las mujeres de ese país.
	} else if strings.EqualFold(p1.Sexo, "femenino") {
		for key, element := range EVANM {
			switch strings.ToLower(key) {
			case strings.ToLower(p1.Pais):
				if element < p1.Edad {
					fmt.Printf("%s, eres una mujer de %d años, nacida en %v. La EVAN promedio para una mujer en %s es de %d años. Has vivido %d años más que el común de la gente para tu género y país.", p1.Nombre, p1.Edad, key, key, element, (-1 * (element - p1.Edad)))
				} else {
					fmt.Printf("%s, eres una mujer de %d años, nacida en %v. La EVAN promedio para una mujer en %s es de %d años. Te quedan aproximademente %d años más por vivir según tu género y país de nacimiento.", p1.Nombre, p1.Edad, key, key, element, element-p1.Edad)
				}
			}
		}
	}
}
